language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11-dev"
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover tests
